mysql_db:
    name: "mysql"
    host: "mysql" # по названию сервиса в докер-компоуз
    port: "3306"
    username: "ruslan"
mongo_db:
    name: "mongo"
    host: "mongo"
    port: "27017"

redis_db:
    host: "redis"
    port: "6379"

http_server:
    host: "localhost"
    port: "8080"
    timeout: "4s"
    idle_timeout: "60s"
    username: "ruslan"

log_level: "debug"