mysql_db:
    name: "mysql"
    host: "host.docker.internal"
    port: "3306"
    username: "ruslan"
    
mongo_db:
    name: "mongo"
    host: "host.docker.internal"
    port: "27017"

redis_db:
    host: "host.docker.internal"
    port: "6379"

http_server:
    host: "localhost"
    port: "8080"
    timeout: "4s"
    idle_timeout: "60s"
    username: "ruslan"

log_level: "debug"