version: '3.1'

services:
  task_manager:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: task_manager
    depends_on:
      - redis
      - mongo
      - mysql
    ports:
      - "8080:8080"
    environment:
      mysql_pass: "${mysql_pass}"
      server_pass: "${server_pass}"
    networks:
      - ps

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
      MYSQL_PASSWORD: "${mysql_pass}"
      MYSQL_USER: "ruslan"
    ports:
      - "3306:3306"
    networks:
      - ps

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_NAME: "mongo"
      MONGO_HOST: "localhost"
    networks:
      - ps

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_NAME: "redis"
      REDIS_HOST: "localhost"
    networks:
      - ps

networks:
  ps: